# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82c477ca9b62c0d7b6d1d6e39e7eaab47afab836d85803770134a5aaeeb0ece41d96facbc4bf1a9049caebfd09d655cdeea9642fcfbdcf0fb40b702e93b3cc23

test:
  secret_key_base: f00fdab92a238b45cdd77b76ccab090050c27e1dda32cb5cb71d36dcdd835da38786c4b93bdb9a68fd9835182eb01ed729a796c234c95385c78ed090878af9cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
